//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using Data.Inteface;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class FoosballWarriorsEntities : DbContext
    {
        public FoosballWarriorsEntities()
            : base("name=FoosballWarriorsEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<PlayedMatch> PlayedMatches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
