//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayedMatch
    {
        public int Id { get; set; }
        public int OffencePlayer1 { get; set; }
        public int DefencePlayer1 { get; set; }
        public int Team1 { get; set; }
        public int ScoreTeam1 { get; set; }
        public int OffencePlayer2 { get; set; }
        public int DefencePlayer2 { get; set; }
        public int Team2 { get; set; }
        public int ScoreTeam2 { get; set; }
        public System.DateTime MatchTime { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Player Player2 { get; set; }
        public virtual Player Player3 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team3 { get; set; }
    }
}
